networks:
  default:
  traefik:
    external: true

services:
  prometheus:
    image: prom/prometheus
    # ports:
    #   - 9090:9090
    volumes:
      - ./generated/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./volumes/prometheus:/prometheus
    networks:
      - traefik
    restart: unless-stopped
    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.http.routers.prometheus.rule=Host(`${PROMETHEUS_DOMAIN}`)"
    #   - "traefik.http.routers.prometheus.entrypoints=websecure"

  grafana:
    image: grafana/grafana
    # ports:
    #   - "3000:3000"  # Expose Grafana web interface
    volumes:
    - ./volumes/grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
    networks:
      - traefik
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`${GRAFANA_DOMAIN}`)"
      - "traefik.http.routers.grafana.entrypoints=websecure"
